Clean up code.

diff --git a/doi2bib b/doi2bib
--- a/doi2bib
+++ b/doi2bib
@@ -42,27 +42,26 @@
 #?   doi2bib <https://github.com/dudektria/doi2bib>
 #?   is licensed under the MIT License.
 
-while getopts ":hv" opt "$@"
-  do
-    case $opt in
-      h)  # help
-        grep "^#?" "$0" | cut -c 4-
-        exit 0
-        ;;
-      v)  # version
-        grep "^#? doi2bib" "$0" | cut -c 4-
-        exit 0
-        ;;
-      \?)
-        echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-      :)
-        echo "Option -$OPTARG requires an argument." >&2
-        exit 1
-        ;;
-    esac
-  done
+while getopts ":hv" opt "$@"; do
+  case $opt in
+    h)  # help
+      grep "^#?" "$0" | cut -c 4-
+      exit 0
+      ;;
+    v)  # version
+      grep "^#? doi2bib" "$0" | cut -c 4-
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
 # recover $@
 shift $((OPTIND-1))
